name: Archive podcast feeds

on:
  workflow_dispatch:

jobs:
  archive-feeds:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Fetch podcast feeds
      run: python feed-archive/step-1-fetch-feeds.py

    - name: Parse podcast feeds
      run: python feed-archive/step-2-parse-feeds.py

    - name: Diff podcast feeds
      run: python feed-archive/step-3-diff-feeds.py

    # - name: Print diffs
    #   run: |
    #     git add feed-archive/*/parsed/diffs/*
    #     git diff --ignore-space-change --cached

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create pull request
      id: pr
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: Update podcast feed archive
        title: Update podcast feed archive
        body: This automated pull request was generated by the "${{ github.workflow }}" [GitHub Actions](https://github.com/critrolesync/critrolesync.github.io/actions) workflow.
        reviewers: jpgill86
        branch: feed-archive
        labels: feed archive update
        delete-branch: true

    - name: Check outputs
      run: |
        echo "Pull request number: ${{ steps.pr.outputs.pull-request-number }}"
        echo "Pull request URL: ${{ steps.pr.outputs.pull-request-url }}"

    # - name: TEST RESULT
    #   run: |
    #     git add *
    #     git diff --ignore-space-change --cached > feed-archive-changes.diff
    #     cat feed-archive-changes.diff
