name: Archive podcast feeds

on:
  schedule:
    - cron: '26 * * * *'
  workflow_dispatch:

jobs:
  archive-feeds:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Fetch podcast feeds
      run: python feed-archive/step-1-fetch-feeds.py

    - name: Parse podcast feeds
      run: python feed-archive/step-2-parse-feeds.py

    - name: Diff podcast feeds
      run: python feed-archive/step-3-diff-feeds.py

    - name: Discard new feed snapshots if there are no parsed changes
      run: |
        count=$(wc -w \
          $(ls feed-archive/critical-role/parsed/diffs/*.diff | tail -n1) \
          $(ls feed-archive/nerdist/parsed/diffs/*.diff | tail -n1) \
          | grep total \
          | tr -d [:alpha:],[:space:])
        echo "New diffs contain ${count} words"
        if [ ${count} = 0 ]; then
          echo "Discarding changes"
          rm -rf feed-archive
          git reset --hard
        else
          echo "Keeping changes"
        fi

    - name: Create pull request
      id: pr
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: Update podcast feed archive
        title: Update podcast feed archive
        body: |
          This automated pull request was generated by the "[${{ github.workflow }}](https://github.com/critrolesync/critrolesync.github.io/actions/workflows/archive-podcast-feeds.yml)" GitHub Actions workflow.
          
          @jpgill86
        branch: update-feed-archive
        labels: feed archive update
        delete-branch: true

    - name: Print pull request information
      run: |
        echo "Pull request number: ${{ steps.pr.outputs.pull-request-number }}"
        echo "Pull request URL: ${{ steps.pr.outputs.pull-request-url }}"

    - name: Show podcast feed changes
      run: git diff --output-indicator-new=" " master update-feed-archive -- *.diff
